source "https://rubygems.org"

gem "rake"
gem "sinatra"
gem "unicorn"
gem "dry-validation"

group :test, :development do
  gem "bundler-audit"
  gem "dawnscanner", require: false
  gem "irb"
  gem "minitest"
  gem "minitest-focus"
  gem "minitest-reporters"
  gem "pry"
  gem "rack-test"
  gem "rdoc"
  gem "rubocop"
  gem "shotgun"
  gem "simplecov"
  gem "simplecov-console", require: false
  gem "webmock" 
end
